### ISSUE TITLE
Wordpress admin password being overwritten during install

### ISSUE THREAD

**Issue by jayfresh** [jbfink/docker-wordpress#3]
Hello, I may have the wrong end of the stick here, but when this image finishes its start.sh script and you visit the website, you are taken through the WP install process. This overwrite the wp-admin password - is that correct?

**Comment by jbfink** [comment]
Hi @jayfresh, the passwords generated by start.sh are ssh for the user account, mysql root, and the password for Wordpress's mysql database -- this is different from the Wordpress admin password itself, which as you've noted you set from the install page. So no overwriting happens. 

Under most circumstances you're not going to need either the mysql root or the Wordpress mysql password -- I echo them to logs and files for convenience, but they're fine to leave alone. 

Please let me know if you test it and find out differently, or if what I've said doesn't make sense. Thanks for trying out docker-wordpress!

**Comment by jbfink** [comment]
Closing this because no action on it for a while.

**Comment by jayfresh** [comment]
Thanks!
