### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by natea** [jbfink/docker-wordpress#4]
When I try to launch a container using the jbfink/wordpress image, when I try to go to the URL, I see the error 'Error establishing a database connection'. Below is what's in the logs. Could it be that the 10s wait time is not sufficient? https://github.com/jbfink/docker-wordpress/blob/master/start.sh#L12

```
ssh user password: aikoo0Fa 
131006 15:58:28 mysqld_safe Logging to syslog. 
131006 15:58:30 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql 
mysql root password: eCheeth0peik 
wordpress password: zah3eep3AKee 
mysqladmin: connect to server at 'localhost' failed 
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' 
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists! 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) 
131006 15:58:42 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended 
/usr/local/lib/python2.7/dist-packages/supervisor-3.0-py2.7.egg/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security. 
'Supervisord is running as root and it is searching ' 
2013-10-06 15:59:25,866 CRIT Supervisor running as root (no user in config file) 
2013-10-06 15:59:26,007 INFO RPC interface 'supervisor' initialized 
2013-10-06 15:59:26,008 CRIT Server 'unix_http_server' running without any HTTP authentication checking 
2013-10-06 15:59:26,008 INFO supervisord started with pid 357 
2013-10-06 15:59:27,016 INFO spawned: 'httpd' with pid 360 
2013-10-06 15:59:27,032 INFO spawned: 'sshd' with pid 361 
2013-10-06 15:59:27,055 INFO spawned: 'mysqld' with pid 362 
2013-10-06 15:59:28,070 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) 
2013-10-06 15:59:28,096 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs) 
2013-10-06 15:59:28,096 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by jbfink** [comment]
Possibly? Last time I did a build the 10s was more than enough, but when I'm at the machine that runs my Docker stuff I will rerun with the 10s to make sure -- you can also change the sleep time yourself, see if that works. It may very well be dependent on the speed of the host machine and I'm being way too conservative with the 10s sleep. Maybe a minute would work?

**Comment by jbfink** [comment]
Hey @natea, I just ssh'd into my docker host and tried it out, no problems on mysql. Could you try extending the time to 30s or 1m and let me know if that solves the problem for you? If so, I will change my script to lengthen the time so that other people don't have the same problem. Thanks!

**Comment by natea** [comment]
yes, after bumping it up to 60 seconds, and now it's establishing the database connection with no errors.

**Comment by natea** [comment]
I think the original 10s is fine. I was just impatient the first time and didn't wait.

**Comment by jbfink** [comment]
Awesome, thanks so much for testing it out. I'll leave it at 10s, until/unless more people report this.
