### ISSUE TITLE
Automatically increase upload_max_filesize in php.ini

### ISSUE THREAD

**Issue by karolisdzeja** [jbfink/docker-wordpress#9]
It'd be nice if it automatically increased the upload_max_filesize in php.ini to something more than 2M. It's 2014, we can go to 20M.

**Comment by jbfink** [comment]
Whoa, it's 2014 already? Man. The future, it is here. 

Agreed! Will fix!

**Comment by jbfink** [comment]
OK, fixed in latest commit. Thanks for the idea!
